### ISSUE TITLE
Add a way to pass arguments to the requests library

### ISSUE THREAD

**Issue by href** [puppet-community/pypuppetdb#31]
We keep our PuppetDB API behind HTTP Basic Auth (with https). As far as I can see there's no possibility for us to use this API. It would be nice if there was a way to pass custom arguments to the requests library for this purpose.

I think this would go nicely with the newly proposed API:

    client = Client(address='https://api.example.org', auth=('user', 'pass'))

**Comment by fgimian** [comment]
I've implemented support for basic auth via commit https://github.com/puppet-community/pypuppetdb/commit/878e2331ef8fd76447f88d930590d9bdd9798de8.  I don't really feel there are any other kwargs you'll need to pass in, so hopefully this covers it :smile: 

Cheers
Fotis
