### ISSUE TITLE
support additional event properties

### ISSUE THREAD

**Issue by jantman** [puppet-community/pypuppetdb#33]
There are a number of properties in the v3 Events endpoint (http://docs.puppetlabs.com/puppetdb/2.0/api/query/v3/events.html) that don't seem to be stored in the Event type:

* containing-class
* file
* line

Support for these would be nice, especially "containing-class". I don't know if I'll get around to a PR for this, but I'll try.

**Comment by fgimian** [comment]
This is now supported via commit https://github.com/puppet-community/pypuppetdb/commit/cf38890e2954897bb8b044853ffccfe79c783393 :smile:
