### ISSUE TITLE
V3 API not correctly returning noop status from latest event.

### ISSUE THREAD

**Issue by gapotts** [puppet-community/pypuppetdb#48]
I discovered this problem when I noticed puppetboard did not properly return a noop status on some of my nodes. When I run the pypuppetdb commands from the command line I see the same behavior, but when I query the puppetdb using curl I clearly see the noop status in the appropriate events.

**Comment by daenney** [comment]
Can you show some examples?

**Comment by gapotts** [comment]
Look at what is reported for pup007.xxx.com below, and compare to the curl output:

Emulating how puppetboard calls pypuppetdb:

>>> from pypuppetdb import connect
>>> nodes = puppetdb.nodes( unreported=3, with_status=True)
>>> for node in nodes:
...   print node, node.status
...
db003.xxx.com changed
db004.xxx.com changed
pup002.xxx.com changed
pup003.xxx.com changed
pup004.xxx.com changed
pup005.xxx.com changed
pup006.xxx.com changed
pup007.xxx.com None


Using curl:

[root@pup005 ~]# curl -G 'http://localhost:8080/v3/events' --data-urlencode 'query=["and", ["=","latest-report?",true], ["=", "status", "noop" ] ]'
[ {
  "containment-path" : [ "Stage[pre]", "Repos", "File[/etc/yum.repos.d/nina.repo]" ],
  "new-value" : "absent",
  "containing-class" : "Repos",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "/etc/yum.repos.d/xxx.repo",
  "property" : "ensure",
  "file" : null,
  "old-value" : "file",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : null,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "File",
  "timestamp" : "2015-03-09T20:35:54.688Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value file, should be absent (noop)"
}, {
  "containment-path" : [ "Stage[pre]", "Repos", "File[/etc/yum.repos.d/ivr.repo]" ],
  "new-value" : "absent",
  "containing-class" : "Repos",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "/etc/yum.repos.d/yyy.repo",
  "property" : "ensure",
  "file" : null,
  "old-value" : "file",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : null,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "File",
  "timestamp" : "2015-03-09T20:35:54.685Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value file, should be absent (noop)"
}, {
  "containment-path" : [ "Stage[pre]", "Repos", "Repos::Make_repo[CentOS-Base.repo]", "File[/etc/yum.repos.d/CentOS-Base.repo]" ],
  "new-value" : "{md5}771d92f98e372f11abf55aae5af113fe",
  "containing-class" : "Repos",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "/etc/yum.repos.d/CentOS-Base.repo",
  "property" : "content",
  "file" : "/etc/puppet/environments/lab/puppet/modules/infra/repos/manifests/make_repo.pp",
  "old-value" : "{md5}5474e7f610487464a1857de299351692",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : 8,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "File",
  "timestamp" : "2015-03-09T20:35:54.756Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007xxx.com",
  "message" : "current_value {md5}5474e7f610487464a1857de299351692, should be {md5}771d92f98e372f11abf55aae5af113fe (noop)"
}, {
  "containment-path" : [ "Stage[main]", "Ops_view_agent", "File[/usr/local/nagios/libexec/check_odi_jobs]" ],
  "new-value" : "{md5}f1ac13738f8e857be7226e31906f5dd4",
  "containing-class" : "Ops_view_agent",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "/usr/local/nagios/libexec/check_xxx_jobs",
  "property" : "content",
  "file" : null,
  "old-value" : "{md5}ef00d3208f0a6d619a57c1dfb0bdda59",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : null,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "File",
  "timestamp" : "2015-03-09T20:36:10.168Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value {md5}ef00d3208f0a6d619a57c1dfb0bdda59, should be {md5}f1ac13738f8e857be7226e31906f5dd4 (noop)"
}, {
  "containment-path" : [ "Stage[main]", "Common", "Common::Utils::Yum_clean_all[get new packs]", "Exec[get new packs]" ],
  "new-value" : [ "0" ],
  "containing-class" : "Common",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "get new packs",
  "property" : "returns",
  "file" : "/etc/puppet/environments/lab/puppet/modules/infra/common/manifests/utils.pp",
  "old-value" : "notrun",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : 212,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "Exec",
  "timestamp" : "2015-03-09T20:35:55.639Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value notrun, should be 0 (noop)"
}, {
  "containment-path" : [ "Stage[main]", "Puppet", "File[/etc/puppet/puppet.conf]" ],
  "new-value" : "{md5}963f3e13944a7cafdca71333ce9712c2",
  "containing-class" : "Puppet",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "/etc/puppet/puppet.conf",
  "property" : "content",
  "file" : "/etc/puppet/environments/lab/puppet/modules/infra/puppet/manifests/init.pp",
  "old-value" : "{md5}cb814e0a902b53eb839d0911c97086ba",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : 42,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "File",
  "timestamp" : "2015-03-09T20:36:01.507Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value {md5}cb814e0a902b53eb839d0911c97086ba, should be {md5}963f3e13944a7cafdca71333ce9712c2 (noop)"
}, {
  "containment-path" : [ "Stage[main]", "Salt::Minion", "Package[salt-minion]" ],
  "new-value" : "latest",
  "containing-class" : "Salt::Minion",
  "report-receive-time" : "2015-03-09T20:36:12.195Z",
  "report" : "81a689081ba39d28cedfd111a5bd01b0870b7327",
  "resource-title" : "salt-minion",
  "property" : "ensure",
  "file" : "/etc/puppet/environments/lab/puppet/modules/infra/salt/manifests/minion.pp",
  "old-value" : "absent",
  "run-start-time" : "2015-03-09T20:35:45.760Z",
  "line" : 24,
  "status" : "noop",
  "run-end-time" : "2015-03-09T20:35:59.822Z",
  "resource-type" : "Package",
  "timestamp" : "2015-03-09T20:36:09.834Z",
  "configuration-version" : "heads/master-0-g878042c",
  "certname" : "pup007.xxx.com",
  "message" : "current_value absent, should be latest (noop)"
} ]

**Comment by daenney** [comment]
Mmm, curious. I thought we handled that. I'll look into it.

**Comment by corey-hammerton** [comment]
The response format of the reports endpoint now returns a noop flag to determine if this report was run in a noop mode. 

With PyPuppetDB 0.2.0 we set ``pypuppetdb.types.Report.status`` to 'noop' if this flag is true, keep it to the regular status field otherwise. This has been tested and verified.
