### ISSUE TITLE
Facts not showing the actual value.

### ISSUE THREAD

**Issue by shanedroid** [puppet-community/pypuppetdb#49]
I am trying to use pypuppetdb to write a simple script to notify others of certain facts on certain nodes. My script is as follows:

https://gist.github.com/anonymous/acc90a6c22533aa9485f

When I run the script, I get an output consisting of the fact name and the fact certname (node-name). Looking at how the facts method is used it appears as though the value should be returned as well?

https://github.com/puppet-community/pypuppetdb/blob/master/pypuppetdb/api/v3.py#L139

For instance if I try to curl for the facts via cli I get back the usual JSON object containing all 3 things.

**Comment by daenney** [comment]
That's because you need to access `fact.name` and `fact.value`. Printing `fact` just gives you the object, in this case the `__str__` or `__unicode__` representation which is made up of the hostname we fetched the fact from and the fact name itself.

**Comment by shanedroid** [comment]
Thank you - did not realize that at first , works perfectly - rtm :)
