### ISSUE TITLE
Maintaining pypuppetdb - looking for volunteers

### ISSUE THREAD

**Issue by daenney** [puppet-community/pypuppetdb#50]
Though it pains me to write this I am no longer able to maintain pypuppetdb.

I have commitments to many open source projects which at this point means I am spread to thin. Paired with no longer having a need to develop this project on a personal or professional basis it has slipped further and further. This is harmful to the project and its continuity.

There are however plenty of people and organisations that rely on this project. As such I am hoping that some will step up and take over from me. I'm more than happy to facilitate discussions or function in an advisory capacity but I can no longer be the driver.

If you'd like to take over I'd like to know a few things:

* Why you want to take over / will be able to work on it
* What your PyPi username is so I can give you upload privileges

I have only one constraint. Pypuppetdb resides in the Puppet-Community Github organisation and I expect it to stay there. It's a project that was started by Puppet community members and that was contributed to by Puppet community members. As such it belongs here.

**Comment by daenney** [comment]
This relates to puppet-community/puppetboard#132.

**Comment by corey-hammerton** [comment]
I volunteer myself to be a maintainer. 

I am working on this project and the puppetboard project, in forks, to make it compatible with puppetdb 3.x and working on that has given me new ideas on the future of the projects. While I lack a diverse set of testing environments and experience working in python I hope that I can learn and grow from these projects

I do not have a PyPi username at the present time but will have one available shortly.

**Comment by daenney** [comment]
Works for me. I've added you to the necessary project teams. Use your new-found power carefully and discuss any major changes with other collaborators first :smile:.

**Comment by corey-hammerton** [comment]
@daenney My PyPi username is coreyhammerton

**Comment by corey-hammerton** [comment]
*nudge* for PyPi permissions

**Comment by daenney** [comment]
Done, you have access now.

**Comment by daenney** [comment]
@corey-hammerton I really need you to start being available in at least #puppetboard on Freenode and preferably also #puppet-community. People need support sometimes when things go wrong but have no way of reaching the maintainer. That's not a good experience.
