### ISSUE TITLE
Get total

### ISSUE THREAD

**Issue by Poil** [puppet-community/pypuppetdb#51]
Hi,

I'm trying to get the total of nodes after this simple query

```python
from pypuppetdb import connect
db = connect()
nodes = db.nodes()

for node in nodes:
  print(node)
```

But nodes doesn't seem to have "include_total" to True, is there anyway to have it ?

Best regards,

**Comment by fgimian** [comment]
Sure, this is easy to do :smile: 

```python
In [1]: from pypuppetdb import connect

In [2]: db = connect()

In [3]: nodes = list(db.nodes())

In [4]: print 'The number of nodes found were {}'.format(len(nodes))
The number of nodes found were 53
```

Keep in mind that nodes returns a generator, so you must explicitly convert it to a list to let the generator complete its iterations and then use the `len` function to count the entries received.

Cheers
Fotis
