### ISSUE TITLE
Support puppetdb 3.0 and new v4 api

### ISSUE THREAD

**Issue by thabend0r** [puppet-community/pypuppetdb#54]
Currently pypuppet breaks with the new puppetdb api 

endpoints have changed and paths have changed

https://docs.puppetlabs.com/puppetdb/3.0/api/query/v4/upgrading-from-v3.html

**Comment by corey-hammerton** [comment]
Just opened https://github.com/puppet-community/pypuppetdb/pull/55 to achieve just that

**Comment by thabend0r** [comment]
Great :D any details when pull request will be honored?

**Comment by corey-hammerton** [comment]
Since I'm a contributor and not a maintainer I do not know. But a release of this should also come with a release of puppetboard to either install specific versions and/or have pull PuppetDB 3.0 support

**Comment by corey-hammerton** [comment]
Also, since I'm now doing more intensive testing and working on the puppetboard project more development work and therefore commits will be submitted. Therefore I have closed https://github.com/puppet-community/pypuppetdb/pull/55 until I've finished by work with the puppetboard

**Comment by Jmeyering** [comment]
Subscribing, Any word on progress here?

**Comment by corey-hammerton** [comment]
https://github.com/puppet-community/pypuppetdb/pull/57 has been opened. Awaiting review and further testing.

**Comment by corey-hammerton** [comment]
PuppetDB 3.x support is implemented in 0.2.0. Backwards compatibility with older versions is removed.
