### ISSUE TITLE
PuppetDB 3.2

### ISSUE THREAD

**Issue by daenney** [puppet-community/pypuppetdb#60]
* Support PuppetDB query params as POST body, to allow for arbitrarily long queries. Previously some clients and proxy servers were truncating or failing on large queries supplied in a GET request. (PDB-1359)
* Added new code_id field in preparation for new filesync service. (PDB-1810)
* Introduce latest_report_status and latest_report_hash to the nodes entity, as projected from the a nodes latest report. (PDB-1820)
* Support extract with no sub-expression. (PDB-1459)

**Comment by corey-hammerton** [comment]
All points listed in the description EXCEPT the last one can be implemented in this project. 

The extract with no sub-expression point can only be applied to the clients.
